#!/bin/bash

set -eu -o pipefail
cd "$(dirname "$(readlink -f "$0")")"/../private_config

### Settings ###
SALT="690342942FA06D75"
ITER="500000"
################

COMMAND=${1}
shift

input_password() {
  local VARIABLE_NAME=${1}
  echo -n "Enter password: "
  builtin read -s "${VARIABLE_NAME}"
  echo
}

case ${COMMAND} in
  unlock)
    echo "Unlocking secrets"
    input_password PASSWORD
    mkdir -p ./decoded
    find ./encoded/ -type f -print0 | xargs -0 -n1 bash -c 'openssl enc -aes-256-cbc -md sha512 -d -a -iter "${3}" -S "${2}" -in "${4}" -out "./decoded/${4##./encoded/}" -pass "pass:${1}"' -- "${PASSWORD}" "${SALT}" "${ITER}"
    ;;

  encrypt)
    echo "Encrypting secrets"
    input_password PASSWORD
    input_password PASSWORD_2
    if [ "${PASSWORD}" != "${PASSWORD_2}" ]; then
      echo "Passwords do not match"
      exit 1
    fi
    find ./decoded/ -type f -print0 | xargs -0 -n1 bash -c 'openssl enc -aes-256-cbc -md sha512 -e -a -iter "${3}" -S "${2}" -in "${4}" -out "./encoded/${4##./decoded/}" -pass "pass:${1}"' -- "${PASSWORD}" "${SALT}" "${ITER}"
    ;;

  remove)
    echo "Remove secrets"
    rm -rf ./decoded
    ;;
esac
