#!/bin/sh

export XDG_CONFIG_HOME="${HOME}/.config"
# export XDG_CACHE_HOME="${HOME}/.cache"
# export XDG_DATA_HOME="${HOME}/.local/share"
# export XDG_STATE_HOME="${HOME}/.local/state"

# rustup
if [ -e "${HOME}/.cargo/env" ]; then
    . "${HOME}/.cargo/env"
fi

# useful script
if [ -d "${HOME}/.bin" ]; then
    export PATH="${PATH}:${HOME}/.bin"
fi

# Antigravity（XDG Base Directory 仕様に沿わないゴミアプリ）
if [ -d "${HOME}/.antigravity/antigravity/bin" ]; then
    export PATH="${HOME}/.antigravity/antigravity/bin:${PATH}"
fi

# SSH_AUTH_SOCK（shenv と同じ内容とすること）
#  Bitwarden が起動している場合は Bitwarden の SSH エージェントを使う
if [ -S "/Users/${USER}/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock" ]; then
    export SSH_AUTH_SOCK="/Users/${USER}/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock"
fi
if [ -S "/Users/${USER}/.bitwarden-ssh-agent.sock" ]; then
    export SSH_AUTH_SOCK="/Users/${USER}/.bitwarden-ssh-agent.sock"
fi
#  SSH で接続していない場合は ssh-agent を起動する
if [ -z "${SSH_CONNECTION}" ] && [ -z "${SSH_AUTH_SOCK:-}" ]; then
    if command -v ssh-agent > /dev/null 2>&1; then
        eval "$(ssh-agent)" > /dev/null 2>&1
    fi
fi

# Homebrew
if [ -x "/opt/homebrew/bin/brew" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv "${SHELL##*/}")"
fi

# その他しょうもない設定
#  https://github.com/aws/aws-cdk/issues/34892
export CDK_DISABLE_CLI_TELEMETRY=true
#  https://github.com/anthropics/claude-code/issues/1455
export CLAUDE_CONFIG_DIR="${XDG_CONFIG_HOME}/claude"
#  https://code.claude.com/docs/ja/monitoring-usage
#  https://code.claude.com/docs/ja/settings#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0
export CLAUDE_CODE_ENABLE_TELEMETRY="0"
